name: Format
on:
  push:
    branches: [dev]
  pull_request:
    branches: [main, dev]

jobs:
  format:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: true
          ref: ${{ github.head_ref }}

      - uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Install pnpm
        uses: pnpm/action-setup@v3
        with:
          version: latest

      - name: Install dependencies
        run: pnpm install

      - name: Format code
        run: pnpm run format

      - name: Commit formatted files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "style: format code" || echo "No changes to commit"

      - name: Checkout to the branch before pushing
        run: git checkout ${{ github.head_ref }}

      - name: Push changes
        run: git push origin ${{ github.head_ref }}